[package]
name = "checkers_cpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui-macroquad = "0.12.0"
tokio = {version = "1.21.2", features=["full"]}
#fastrand = "1.8.0"
